# Generated by Django 2.0.4 on 2019-02-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCustom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cities.city',),
        ),
        migrations.CreateModel(
            name='DistrictCustom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cities.district',),
        ),
        migrations.CreateModel(
            name='PostalCodeCustom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cities.postalcode',),
        ),
        migrations.CreateModel(
            name='RegionCustom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cities.region',),
        ),
        migrations.CreateModel(
            name='SubRegionCustom',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cities.subregion',),
        ),
    ]
