version: '3.6'
services:
  nginx:
    image: registry.gitlab.com/rushil0195/rentality/nginx:v0.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/static
      - media:/media
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
  web:
    image: registry.gitlab.com/rushil0195/rentality/web:v3.1
    volumes:
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
    depends_on:
      - postgres
      - elasticsearch
      - migration
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - WEB_ENV
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_USER
    deploy:
      # Number of Replicas in production
      replicas: 3
      # resources:
        # cpus: Percentage of CPU usage
        # memory: Memory size
        # limits: Maximum allowable resources.
        # limits:
        #   cpus: '0.3'
        #   memory: 200M
        # Minimum resources that are always allocated to a container. Uncomment if needed
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3 # Default is never give up.
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
  elasticsearch:
    # Set vm.max_map_count=262144 in /etc/sysctl.conf
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - cluster.name=rentality-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  migration:
    image: registry.gitlab.com/rushil0195/rentality/web:v3.1
    volumes:
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
    depends_on:
      - postgres
      - elasticsearch
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - WEB_ENV
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_USER
    entrypoint: python manage.py migrate --noinput; python manage.py collectstatic --noinput

secrets:
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
  WEB_ENV:
    file: ./secrets/WEB_ENV
  RABBITMQ_DEFAULT_USER:
    file: ./secrets/RABBITMQ_DEFAULT_USER
  RABBITMQ_DEFAULT_PASS:
    file: ./secrets/RABBITMQ_DEFAULT_PASS
volumes:
  pgdata:
  esdata:
  static:
  media: