stages:
  - build
  - release

image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

before_script:
  - apk add --update python3 py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make && pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - docker
  script:
    - make ci-build
  only:
    - staging
    - master

release:
  stage: release
  tags:
    - docker
  script:
    - make publish
  only:
    - master
