stages:
  - build
  - release

image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.12-dind

before_script:
  - apk add --update python3 py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make && pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t rentality/backend-common:latest -f ./backend/Dockerfile.common --no-cache ./backend
    - COMMIT_BRANCH="$CI_COMMIT_BRANCH" GIT_HEAD_HASH="$CI_COMMIT_SHORT_SHA" docker-compose -f docker-compose.prod-build.yml build --no-cache --parallel
  only:
    - staging
    - master

release:
  stage: release
  tags:
    - docker
  script:
    - COMMIT_BRANCH="$CI_COMMIT_BRANCH" GIT_HEAD_HASH="$CI_COMMIT_SHORT_SHA" docker-compose -f docker-compose.prod-build.yml push
  only:
    - staging
    - master
