stages:
  - build

image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

  CONTAINER_TEST_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  CONTAINER_STAGING_RELEASE_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:staging-latest
  CONTAINER_RELEASE_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:latest

  CONTAINER_TEST_WEB_IMAGE: $CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_SLUG
  CONTAINER_STAGING_RELEASE_WEB_IMAGE: $CI_REGISTRY_IMAGE/web:staging-latest
  CONTAINER_RELEASE_WEB_IMAGE: $CI_REGISTRY_IMAGE/web:latest

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build
    - docker tag $CONTAINER_RELEASE_WEB_IMAGE $CONTAINER_TEST_WEB_IMAGE
    - docker push $CONTAINER_TEST_WEB_IMAGE
    - docker tag $CONTAINER_TEST_WEB_IMAGE $CONTAINER_STAGING_RELEASE_WEB_IMAGE
    - docker push $CONTAINER_STAGING_RELEASE_WEB_IMAGE
    - docker tag $CONTAINER_RELEASE_FRONTEND_IMAGE $CONTAINER_TEST_FRONTEND_IMAGE
    - docker push $CONTAINER_TEST_FRONTEND_IMAGE
    - docker tag $CONTAINER_TEST_FRONTEND_IMAGE $CONTAINER_STAGING_RELEASE_FRONTEND_IMAGE
    - docker push $CONTAINER_STAGING_RELEASE_FRONTEND_IMAGE
  only:
    - staging
