version: '3.6'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/config/localhost.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
    depends_on:
      - web
  postgres:
    image: mdillon/postgis:9.5-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    ports:
      - 5431:5432
    volumes:
      - ./secrets/POSTGRES_USER:/run/secrets/POSTGRES_USER
      - ./secrets/POSTGRES_PASSWORD:/run/secrets/POSTGRES_PASSWORD
      - ./secrets/POSTGRES_DB:/run/secrets/POSTGRES_DB
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  web:
    build: ./src
    image: registry.gitlab.com/rushil0195/rentality/web:latest
    volumes:
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
      - ./secrets:/run/secrets
      - ./src:/rentality/src
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "8001:8000"
volumes: 
  pgdata:
  esdata:
  static:
  media: