version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media
    depends_on:
      - web
  postgres:
    image: mdillon/postgis:10-alpine
    env_file:
      - ./secrets/postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  web:
    build: ./src
    image: registry.gitlab.com/rushil0195/rentality/web:latest
    env_file:
      - ./secrets/web.env
      - ./secrets/postgres.env
    volumes:
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
    depends_on:
      - postgres
      - elasticsearch
volumes: 
  pgdata:
  esdata:
  static:
  media: