version: '3.6'
services:
  nginx:
    build: ./nginx
    image: registry.gitlab.com/rushil0195/rentality/nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/config/common.conf:/etc/nginx/conf.d/common.conf
      - ./nginx/config/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./static_dev/static_root:/static
      - ./static_dev/media_root:/media
    depends_on:
      - web
#      - sys_monitor
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    ports:
      - 5431:5432
    volumes:
      - ./secrets/POSTGRES_USER:/run/secrets/POSTGRES_USER
      - ./secrets/POSTGRES_PASSWORD:/run/secrets/POSTGRES_PASSWORD
      - ./secrets/POSTGRES_DB:/run/secrets/POSTGRES_DB
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    # Set vm.max_map_count=262144 in /etc/sysctl.conf
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - "cluster.name=rentality-cluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    ports:
      - 5601:5601
#  timeseriesdb:
#    image: timescale/timescaledb:1.0.0-pg10
#    environment:
#      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
#      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
#      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
#    ports:
#      - 5430:5432
#    volumes:
#      # FIXME: add settings
#      - ./secrets/POSTGRES_USER:/run/secrets/POSTGRES_USER
#      - ./secrets/POSTGRES_PASSWORD:/run/secrets/POSTGRES_PASSWORD
#      - ./secrets/POSTGRES_DB:/run/secrets/POSTGRES_DB
#      - tsdbdata:/var/lib/postgresql/data
  web:
    build: ./src
    image: registry.gitlab.com/rushil0195/rentality/web:latest
    volumes:
      - ./static_dev/static_root:/rentality/static_dev/static_root
      - ./static_dev/media_root:/rentality/static_dev/media_root
      - ./secrets:/run/secrets
      - ./src:/rentality/src
    depends_on:
      - postgres
      - elasticsearch
#      - timeseriesdb
      - rabbitmq
    ports:
      - "8001:8000"
    entrypoint: ['./entrypoint.dev.sh']
#  sys_monitor:
#    image: grafana/grafana:5.3.1
#    ports:
#      - 3000:3000
#    depends_on:
#      - postgres
#      - timeseriesdb
  # FIXME: add rabbitmq settings
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "15672:15672"
volumes:
  pgdata:
  esdata:
  tsdbdata: