version: '3'
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/rentality/src
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
    ports:
      - 8001:8000