version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media
    depends_on:
      - web
  postgres:
    image: mdillon/postgis:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  web:
    build: ./src
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DELETED_USER_PASS: "${DELETED_USER_PASS}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      DEBUG: "${DEBUG}"
      OAUTH_DETAILS: "${OAUTH_DETAILS}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      OAUTH_FACEBOOK_SECRET: "${OAUTH_FACEBOOK_SECRET}"
      OAUTH_FACEBOOK_CLIENT_ID: "${OAUTH_FACEBOOK_CLIENT_ID}"
      OAUTH_GOOGLE_SECRET: "${OAUTH_GOOGLE_SECRET}"
      OAUTH_GOOGLE_CLIENT_ID: "${OAUTH_GOOGLE_CLIENT_ID}"
      OAUTH_TWITTER_SECRET: "${OAUTH_TWITTER_SECRET}"
      OAUTH_TWITTER_CLIENT_ID: "${OAUTH_TWITTER_CLIENT_ID}"
      OAUTH_INSTAGRAM_SECRET: "${OAUTH_INSTAGRAM_SECRET}"
      OAUTH_INSTAGRAM_CLIENT_ID: "${OAUTH_INSTAGRAM_CLIENT_ID}"
      OAUTH_PINTEREST_SECRET: "${OAUTH_PINTEREST_SECRET}"
      OAUTH_PINTEREST_CLIENT_ID: "${OAUTH_PINTEREST_CLIENT_ID}"
    volumes:
      - static:/rentality/static_dev/static_root
      - media:/rentality/static_dev/media_root
    depends_on:
      - postgres
      - elasticsearch
volumes: 
  pgdata:
  esdata:
  static:
  media: