# Generated by Django 2.2.10 on 2020-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20200413_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseprofile',
            name='seo',
            field=models.BooleanField(default=False, help_text='Optimize listing for seo.'),
        ),
        migrations.AddField(
            model_name='houseprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='houseprofile',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher number sets higher priority'),
        ),
    ]
