# Generated by Django 2.0.4 on 2018-04-30 04:15

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_auto_20180430_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_num', models.CharField(blank=True, max_length=15, verbose_name='contact number')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1, verbose_name='sex')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='HousePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.PositiveIntegerField()),
                ('move_in_date', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('move_out_date', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(choices=[('A', 'Whole Apartment'), ('B', 'Whole House'), ('C', 'Room in Share-house with Private bathroom'), ('D', 'Room in Share-house with Shared bathroom'), ('E', 'Student Accommodation'), ('F', 'Home Stay'), ('G', 'Granny Flat'), ('O', 'Other')], default='A', max_length=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist', models.ManyToManyField(blank=True, to='house.House')),
            ],
        ),
    ]
