# Generated by Django 2.0.4 on 2018-05-01 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0004_auto_20180501_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepreference',
            name='locations',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
    ]
