# Generated by Django 2.0.4 on 2018-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0005_auto_20180501_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepreference',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('S', 'Selected'), ('P', 'Published')], default='I',
                                   max_length=1),
        ),
    ]
