# Generated by Django 2.0.4 on 2018-11-22 19:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import essentials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrivacySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attribute', models.CharField(max_length=20)),
                ('setting', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NM', 'New Message'), ('RL', 'Requests'), ('OF', 'Offers')], max_length=3)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('landing_url', models.URLField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('verbose_name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=20)),
                ('doc', models.FileField(upload_to=essentials.models.get_policy_doc_path)),
                ('html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('L', 'Legacy')], max_length=1)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('parent_policy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.Policy')),
            ],
        ),
    ]
