# Generated by Django 2.0.4 on 2019-02-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20181122_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('TnC', 'Terms and Conditions'), ('ToS', 'Terms of Service'), ('PP', 'Privacy Policy'), ('CP', 'Cookies Policy'), ('CanP', 'Cancellation Policy')], default='ToS', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='code_name',
            field=models.CharField(help_text='For internal references (Short Verbose)', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='version',
            field=models.CharField(help_text="Don't use any special characters.", max_length=20, unique=True),
        ),
    ]
