# Generated by Django 2.0.4 on 2018-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('essentials', '0002_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
