# Generated by Django 2.0.4 on 2018-11-06 11:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('keywords', models.TextField(help_text='Separate the keywords using comma')),
                ('description', models.CharField(help_text='Page Meta Description for SEO', max_length=160)),
                ('abstract', models.CharField(help_text='Used for preview', max_length=250)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher number sets higher priority')),
                ('thumbnail', models.ImageField(upload_to=blog.models.get_article_thumbnail_path)),
                ('tags', models.TextField(help_text='Verbose Tags to find similar articles [Separate the tags using comma]')),
                ('active', models.BooleanField(default=False, help_text='Set to True to publish the article')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
