# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_accountdetail_fee'),
        ('business_core', '0002_auto_20200413_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='business_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='business_core.BusinessModelConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='cancellation_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='business_core.CancellationPolicy'),
            preserve_default=False,
        ),
    ]
