# Generated by Django 2.2.10 on 2020-10-05 02:28

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200413_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
