# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0003_auto_20190205_2156'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Verbose identifier used internally', max_length=10, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(help_text='This will be shown to the user.')),
                ('constraints_model', models.CharField(choices=[('A', 'Validation constraint 1.1')], help_text='Defines constraints unique to business model', max_length=1, verbose_name='Validation constraints model')),
                ('behaviour', models.CharField(choices=[('A', 'Business Constraints A')], help_text='Defines behaviours unique to business model', max_length=1)),
                ('financial_model', models.CharField(choices=[('A', 'Financial Model 1.1')], help_text='Defines attributes for financial handling unique to business model', max_length=1, verbose_name='Financial constraints model')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_core.BusinessModelConfiguration')),
                ('country', models.ForeignKey(blank=True, help_text="Select country to constraint this configuration to the Home Owner's Bank account location.", null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_COUNTRY_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('config_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_core.ConfigProfile')),
                ('house_location_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'cities'), ('model', 'country')), models.Q(('app_label', 'cities'), ('model', 'region')), models.Q(('app_label', 'cities'), ('model', 'city')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_location_restrictions', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.TextField(verbose_name='Policy Name')),
                ('code', models.CharField(help_text='Verbose identifier used internally', max_length=10, unique=True)),
                ('description', models.TextField()),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('behaviour', models.CharField(choices=[('A', 'Cancellation behaviour A')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('official_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_policies', to='essentials.Policy')),
            ],
        ),
        migrations.AddField(
            model_name='businessmodelconfiguration',
            name='cancellation_policies',
            field=models.ManyToManyField(to='business_core.CancellationPolicy'),
        ),
    ]
