# Generated by Django 2.2.10 on 2020-04-11 19:06

from django.db import migrations


def create_default_cancellation_policies(apps, schema_editor):
    OldCancellationPolicy = apps.get_model('house', 'CancellationPolicy')
    CancellationPolicy = apps.get_model('business_core', 'CancellationPolicy')
    for policy in OldCancellationPolicy.objects.all():
        CancellationPolicy.objects.create(
            id=policy.id,
            code=policy.verbose.split(' ')[0].lower(),
            verbose=policy.verbose,
            description=policy.description,
            properties=policy.properties,
            behaviour='A',
            official_policy=policy.official_policy
        )


def create_default_business_config(apps, schema_editor):
    CancellationPolicy = apps.get_model('business_core', 'CancellationPolicy')
    can_policies = CancellationPolicy.objects.all()

    BusinessModelConfig = apps.get_model('business_core', 'BusinessModelConfiguration')
    prev_config = {
        "financial": {
            "attr": {"tenant_charge": 8, "homeowner_charge": 10}
        }, "constraints": {
            "attr": {"min_stay": 28, "max_buffer": 210, "min_buffer": 4, "bookings_buffer": 1}
        }
    }
    b_model = BusinessModelConfig.objects.create(
        id=1, verbose="Business Model A", code="legacy", meta=prev_config,
        description="Behaviour for Legacy objects",
        constraints_model='A',
        behaviour='A',
        financial_model='A'
    )
    for can_policy in can_policies:
        b_model.cancellation_policies.add(can_policy)


class Migration(migrations.Migration):
    dependencies = [
        ('business_core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_cancellation_policies),
        migrations.RunPython(create_default_business_config),
    ]
