# Generated by Django 2.0.4 on 2019-01-31 08:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
