# Generated by Django 2.0.4 on 2019-03-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('user_custom', '0003_auto_20190131_0834'),
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='account',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('B', 'Business'), ('I', 'Individual')], default='I', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_postcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='cities.PostalCode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway', default=1),
        ),
    ]
