# Generated by Django 2.2.10 on 2020-04-12 17:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('user_custom', '0003_auto_20190131_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='account',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('B', 'Business'), ('I', 'Individual')], default='I', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_postcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities.PostalCode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway', default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
