# Generated by Django 2.0.4 on 2019-03-05 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_auto_20190131_0834'),
        ('admin_custom', '0003_paymentgateway')
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='account',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_custom.PaymentGateway', default=1),
        ),
    ]
