# Generated by Django 2.0.4 on 2019-04-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0005_auto_20190320_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway'),
        ),
    ]
