# Generated by Django 2.0.4 on 2019-04-18 11:13

from django.db import migrations, models
import django.db.models.deletion
# from payment_gateway.adapters.stripe import get_all_accounts

# FIXME: URGENT
def initialize_country_for_users(apps, schema_editor):
    Account = apps.get_model('user_custom', 'Account')
    Country = apps.get_model('cities', 'Country')
    # accounts = get_all_accounts()
    # for account in accounts.data:
    #     try:
    #         user_account = Account.objects.get(details__account_id=account.id)
    #         user_profile = user_account.user.userprofile
    #         country = Country.objects.get(code=account.country)
    #         user_profile.billing_country = country
    #         user_profile.save()
    #     except (Account.DoesNotExist, Country.DoesNotExist) as e:
    #         continue


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0005_auto_20190320_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway'),
        ),
        migrations.RunPython(initialize_country_for_users)
    ]
