# Generated by Django 2.2.10 on 2020-02-28 10:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0006_auto_20190418_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
