# Generated by Django 2.0.4 on 2018-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='shortlist',
            field=models.ManyToManyField(blank=True, to='tenant.HousePreference'),
        ),
    ]
