# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Internal Identifier', max_length=10, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(help_text='For internal data and financial assessment only. This should not be used to store any data required for or by the payment gateway for monetary transactions.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(help_text='Holds information required by the payment gateway to work in the selected country.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text="Select country for this Payment Gateway used in reference to the Home Owner's Billing account location.", on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_COUNTRY_MODEL)),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway')),
            ],
            options={
                'unique_together': {('payment_gateway', 'country')},
            },
        ),
        migrations.CreateModel(
            name='LocationRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('house_location_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'cities'), ('model', 'country')), models.Q(('app_label', 'cities'), ('model', 'region')), models.Q(('app_label', 'cities'), ('model', 'city')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pg_location_restrictions', to='contenttypes.ContentType')),
                ('payment_gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.Profile')),
            ],
        ),
    ]
