# Generated by Django 2.2.10 on 2020-04-12 02:03

from django.db import migrations


def populate_for_legacy_data(apps, schema_editor):
    PaymentGateway = apps.get_model('payment_gateway', 'PaymentGateway')
    PGProfile = apps.get_model('payment_gateway', 'Profile')
    LocationRestriction = apps.get_model('payment_gateway', 'LocationRestriction')
    stripe = PaymentGateway.objects.create(id=1, name='Stripe Legacy', code='stripe_LG', meta={})
    Country = apps.get_model('cities', 'Country')
    profile = PGProfile.objects.create(
        id=1,
        payment_gateway=stripe,
        country=Country.objects.get(code='AU'),
        meta={},
    )
    LocationRestriction.objects.create(
        payment_gateway_profile=profile,
    )


def populate_default_data(apps, schema_editor):
    PaymentGateway = apps.get_model('payment_gateway', 'PaymentGateway')
    PGProfile = apps.get_model('payment_gateway', 'Profile')
    LocationRestriction = apps.get_model('payment_gateway', 'LocationRestriction')
    stripe = PaymentGateway.objects.create(id=2, name='Stripe', code='stripe_v2', meta={})
    Country = apps.get_model('cities', 'Country')
    config = {
        "home_owner": {
            "bank_account": {
                "support": [],
                "required_fields": {
                    "token": {"type": "string", "verbose": "token"}
                }
            }, "required_fields": {
                "failure_url": {"type": "string", "regex": "(/(/|-|[a-z]|[0-9])$)", "verbose": "Failure URL"},
                "success_url": {"type": "string", "regex": "(/(/|-|[a-z]|[0-9])$)", "verbose": "Success URL"}
            }
        }
    }
    profile = PGProfile.objects.create(
        id=2,
        payment_gateway=stripe,
        country=Country.objects.get(code='AU'),
        meta=config,
    )
    LocationRestriction.objects.create(
        payment_gateway_profile=profile,
        default=True,
        active=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_for_legacy_data),
        migrations.RunPython(populate_default_data),
    ]
