# Generated by Django 2.0.4 on 2019-01-31 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_application'),
        ('application', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='billing_model',
            field=models.CharField(choices=[('A', '4 weeks of payment only')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(default='S', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fee',
            name='active',
            field=models.BooleanField(default=False, help_text='A house/application can have different Fee objects attached. You can set it as the default.', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='order',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.Application'),
        ),
    ]
