# Generated by Django 2.0.4 on 2019-01-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.Application'),
        ),
    ]
