# Generated by Django 2.0.4 on 2019-03-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190322_0814'),
        ('billing', '0004_paymentgateway'),
        # To first transfer data from Order to PaymentGatewayTransaction and/or LedgerRecord
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='application',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
