# Generated by Django 2.0.4 on 2019-01-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('promotions', '0001_initial'),
        ('tenant', '0002_auto_20181122_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='promotional_code',
            field=models.ManyToManyField(blank=True, to='promotions.PromotionalCode'),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.TenantProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('house', 'tenant')},
        ),
    ]
