# Generated by Django 2.0.4 on 2019-03-20 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def populate_default_cancellation_policy(apps, schema_editor):
    AccountDetail = apps.get_model('application', 'AccountDetail')
    CancellationPolicy = apps.get_model('business_core', 'CancellationPolicy')
    for account_detail in AccountDetail.objects.all():
        account_detail.cancellation_policy = CancellationPolicy.objects.get(
            id=account_detail.application.house_meta['cancellation_policy']['id']
        )
        account_detail.save() 
    # FIXME: @pranav Get cancellation policy from house meta, and set the is directly.
    pass


def populate_state_history(apps, schema_editor):
    # FIXME: @pranav Create relevant entries in Application state
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('business_core', '0001_initial'),
        ('application', '0002_auto_20190131_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='fee',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='business_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='business_core.BusinessModelConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='cancellation_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    to='business_core.CancellationPolicy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='house_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Frozen information of house',
                                                                 null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 help_text='Additional details provided in regards to the application',
                                                                 null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('T', 'Timeout'),
                                            ('E', 'Transaction Error'), ('B', 'Booked')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='tenant_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                 help_text='Additional details provided by the tenant',
                                                                 null=True),
        ),
        migrations.AlterField(
            model_name='applicationstate',
            name='new_state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('T', 'Timeout'),
                                            ('E', 'Transaction Error'), ('B', 'Booked')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicationstate',
            name='old_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='application.ApplicationState'),
        ),
        migrations.RunPython(populate_default_cancellation_policy),
        migrations.RunPython(populate_state_history)
    ]
