# Generated by Django 2.0.4 on 2019-03-22 08:14

from django.db import migrations


def populate_default_cancellation_policy(apps, schema_editor):
    AccountDetail = apps.get_model('application', 'AccountDetail')
    CancellationPolicy = apps.get_model('business_core', 'CancellationPolicy')
    for account_detail in AccountDetail.objects.all():
        account_detail.cancellation_policy = CancellationPolicy.objects.get(
            id=account_detail.application.house_meta['cancellation_policy']['id']
        )
        account_detail.save()


def populate_state_history(apps, schema_editor):
    Order = apps.get_model('billing', 'Order')
    ApplicationState = apps.get_model('application', 'ApplicationState')
    orders = Order.objects.all()
    for order in orders:
        ApplicationState.objects.create(
            application=order.application, 
            old_state=None, 
            new_state='B',
            actor=order.application.tenant.user
        )


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190320_0058'),
    ]

    operations = [
        migrations.RunPython(populate_default_cancellation_policy),
        migrations.RunPython(populate_state_history)
    ]
