# Generated by Django 2.2.10 on 2020-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190322_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('E', 'Error'), ('B', 'Booked'), ('C', 'Cancelled'), ('O', 'In-Effect/In-Stay'), ('Z', 'Complete'), ('X', 'In-Dispute'), ('R', 'Dispute Resolved')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='applicationstate',
            name='new_state',
            field=models.CharField(choices=[('I', 'Incomplete'), ('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('E', 'Error'), ('B', 'Booked'), ('C', 'Cancelled'), ('O', 'In-Effect/In-Stay'), ('Z', 'Complete'), ('X', 'In-Dispute'), ('R', 'Dispute Resolved')], max_length=1),
        ),
    ]
