# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0003_homeownerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeownerprofile',
            name='account_id',
        ),
    ]
