# Generated by Django 2.0.4 on 2019-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0003_homeownerprofile_user'),
        ('user_custom', '0005_auto_20190320_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeownerprofile',
            name='account_id',
        ),
    ]
