# Generated by Django 2.2.10 on 2020-04-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_custom', '0003_auto_20190131_0834'),
        ('application', '0004_auto_20200411_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('P', 'Payout - Transaction from Rentality to Home Owner'), ('C', 'Pay-in - Transaction from Tenant to Rentality'), ('R', 'Refund - Transaction from Rentality to Tenant'), ('HT', 'Virtual Transfer from Rentality to Home-owner Virtual Account'), ('RHT', 'Virtual Transfer from Home-owner Virtual Account to Rentality'), ('TT', 'Virtual Transfer from Tenant Virtual Account to Rentality'), ('RTT', 'Virtual Transfer from Rentality to Tenant Virtual Account')], max_length=3)),
                ('transaction_id', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.Application')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_custom.Account')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(choices=[('Cr', 'Credit'), ('De', 'Debit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pg_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='financials.PaymentGatewayTransaction', verbose_name='Payment Gateway Transaction')),
            ],
        ),
    ]
