# Generated by Django 2.0.4 on 2019-03-20 00:51

from django.db import migrations, models
import django.db.models.deletion


def migrate_billing_data(apps, schema_editor):
    pass
    # FIXME: @pranav


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_custom', '0005_auto_20190320_1817'),
        ('payment_gateway', '0001_initial'),
        ('application', '0002_auto_20190131_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(choices=[('Cr', 'Credit'), ('De', 'Debit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('transaction_type', models.CharField(max_length=2)),
                ('transaction_id', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.Application')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_custom.Account')),
            ],
        ),
        migrations.AddField(
            model_name='ledgerrecord',
            name='pg_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financials.PaymentGatewayTransaction', verbose_name='Payment Gateway Transaction'),
        ),
        migrations.RunPython(migrate_billing_data)
    ]
