# Generated by Django 2.0.4 on 2018-11-08 16:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import house.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_owner', '0001_initial'),
        ('essentials', '0001_initial'),
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.PositiveIntegerField()),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='stay dates')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('periodic', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.TextField(verbose_name='Policy Name')),
                ('description', models.TextField()),
                ('characteristics', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('official_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=50)),
                ('system_default', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('furnished', models.BooleanField(default=False)),
                ('address_hidden', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rent', models.PositiveSmallIntegerField(default=0)),
                ('min_stay', models.PositiveSmallIntegerField(blank=True, help_text='in weeks', null=True)),
                ('max_stay', models.PositiveSmallIntegerField(blank=True, help_text='in weeks', null=True)),
                ('other_rules', models.TextField(blank=True)),
                ('other_people_description', models.TextField(blank=True)),
                ('neighbourhood_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('P', 'Published'), ('D', 'Deleted')], default='I', max_length=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cancellation_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='house.CancellationPolicy')),
                ('facilities', models.ManyToManyField(to='house.Facility')),
                ('home_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='home_owner.HomeOwnerProfile', verbose_name='property owner')),
                ('home_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='house.HomeType', verbose_name='Home Type')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities.PostalCode', verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='HouseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('comment', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=house.models.get_file_path)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourhoodDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=50)),
                ('system_default', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose', models.CharField(max_length=50)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='houserule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.Rule'),
        ),
        migrations.AddField(
            model_name='house',
            name='neighbourhood_facility',
            field=models.ManyToManyField(blank=True, to='house.NeighbourhoodDescriptor'),
        ),
        migrations.AddField(
            model_name='house',
            name='rules',
            field=models.ManyToManyField(through='house.HouseRule', to='house.Rule'),
        ),
        migrations.AddField(
            model_name='availability',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House'),
        ),
        migrations.AddField(
            model_name='application',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='house.House'),
        ),
    ]
