# Generated by Django 2.0.4 on 2018-11-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('house', '0001_initial'),
        ('billing', '0002_order_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstate',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Fee'),
        ),
        migrations.AddField(
            model_name='application',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House'),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.TenantProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='houserule',
            unique_together={('house', 'rule')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('house', 'tenant')},
        ),
    ]
