# Generated by Django 2.0.4 on 2018-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20181122_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='House Description'),
        ),
    ]
