# Generated by Django 2.0.4 on 2018-11-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('house', '0002_auto_20181106_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tenant.TenantProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('house', 'tenant')},
        ),
    ]
