# Generated by Django 2.0.4 on 2018-05-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('house', '0003_auto_20180430_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='house.RoomType',
                                    verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('R', 'Rule'), ('F', 'Facility'), ('T', 'Tenant Preference')],
                                   max_length=1),
        ),
    ]
