# Generated by Django 2.0.4 on 2018-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('house', '0005_auto_20180521_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('R', 'Preferences'), ('F', 'Facility')], max_length=1),
        ),
    ]
