# Generated by Django 2.0.4 on 2019-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20190131_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='periodic',
            field=models.BooleanField(default=False, verbose_name='Make the selected dates available every year'),
        ),
    ]
