# Generated by Django 2.0.4 on 2019-03-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0001_initial'),
        ('house', '0006_auto_20190219_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='business_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='business_core.BusinessModelConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='can_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_core.CancellationPolicy'),
        ),
    ]
