# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0001_initial'),
        ('house', '0006_auto_20190219_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='official_policy',
        ),
        migrations.AddField(
            model_name='house',
            name='business_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='business_core.BusinessModelConfiguration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='local_timezone',
            field=models.CharField(default='Australia/Melbourne', help_text='Pytz compliant value', max_length=50),
            preserve_default=False,
        ),
    ]
