# Generated by Django 2.0.4 on 2019-03-20 20:02

from django.db import migrations, models
import django.db.models.deletion


def migrate_cancellation_policy(apps, schema_editor):
    # FIXME: @pranav migrate cancellation policies here
    # Old field cancellation_policy; new field can_policy; set new field to old value by pk!

    PaymentGateway = apps.get_model('house', 'PaymentGateway')
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190320_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities.PostalCode', verbose_name='location'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_cancellation_policy),
    ]
