# Generated by Django 2.2.10 on 2020-04-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
        ('house', '0007_auto_20200413_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_gateway.PaymentGateway'),
        ),
        migrations.AlterField(
            model_name='house',
            name='access_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_core.CancellationPolicy'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities.PostalCode', verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='neighbourhood_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='other_people_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='other_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('I', 'Inactive'), ('P', 'Published'), ('D', 'Deleted'), ('B', 'Blocked')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
    ]
