# Generated by Django 2.0.4 on 2019-03-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190320_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='official_policy',
        ),
        migrations.RemoveField(
            model_name='house',
            name='cancellation_policy',
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='can_policy',
            new_name='cancellation_policy',
        ),
    ]
