# Generated by Django 2.0.4 on 2019-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20190320_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='access_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='neighbourhood_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='other_people_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='other_rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
