from rest_framework import serializers

"""
Refer to - https://www.django-rest-framework.org/api-guide/serializers/#customizing-listserializer-behavior

The example in documentation needs some changes -
    -   Example : expects id (for database) from the frontend.
        Converted to : ID should be is read-only and is auto generated by the system.
    -   Example : Deletes are implicit while updating.
        Converted to : Cannot delete via update query and cannot mass delete. Updates can only create or
        change values in reference to an id.

Usage Example -
    class AwesomeSerializer(serializers.Serializer):
        class Meta:
            fields = ...
            list_serializer_class = AwesomeListSerializer
"""


class FullUpdateListSerializer(serializers.ListSerializer):
    """
    Creates, Updates and Deletes
    """

    default_error_messages = {
        'invalid_parameter': 'Invalid Parameters',
    }

    def update(self, instances, validated_data):
        old_mapping = {item.id: item for item in instances}

        ret = []
        for data in validated_data:
            try:
                _id = data['id']
            except KeyError:
                # create
                ret.append(self.child.create(data))
            else:
                try:
                    ret.append(self.child.update(old_mapping[_id], data))
                except KeyError:
                    self.fail('invalid_parameter')
        # No deletions

        return ret


class CreateUpdateListSerializer(serializers.ListSerializer):
    """
    Creates and Updates
    """
    default_error_messages = {
        'invalid_parameter': 'Invalid Parameters',
    }

    def update(self, instances, validated_data):
        old_mapping = {item.id: item for item in instances}

        ret = []
        for data in validated_data:
            try:
                _id = data['id']
            except KeyError:
                ret.append(self.child.create(data))
            else:
                try:
                    ret.append(self.child.update(old_mapping[_id], data))
                except KeyError:
                    self.fail('invalid_parameter')
        # No deletions

        return ret


class CreateListSerializer(serializers.ListSerializer):
    """
    Creates Only

    Override and define model_klass
    """

    @property
    def model_klass(self):
        raise NotImplementedError

    def create(self, validated_data):
        data = [self.model_klass(**item) for item in validated_data]
        return self.model_klass.objects.bulk_create(data)

    def update(self, instance, validated_data):
        raise NotImplementedError

    @classmethod
    def init(cls, model):
        """
        Initialize this List serializer with parent model serializer
        :param model: ModelSerializer
        :return: Child class of CreateUpdateListSerializer
        """

        class _CustomListSerializer(cls):
            model_klass = model


class UpdateListSerializer(serializers.ListSerializer):
    default_error_messages = {
        'invalid_parameter': 'Invalid Parameters',
    }

    def update(self, instances, validated_data):
        # Maps for id->instance and id->data item.
        item_mapping = {item.id: item for item in instances}
        data_mapping = {item['id']: item for item in validated_data}

        # Perform creations and updates.
        ret = []
        for item_id, data in data_mapping.items():
            item = item_mapping.get(item_id, None)
            if item is None:
                self.fail('invalid_parameter')
            else:
                ret.append(self.child.update(item, data))
        return ret

    def create(self, validated_data):
        self.fail('invalid_parameter')
