# Generated by Django 2.0.4 on 2018-11-06 11:49

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_auto_20181106_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_num', models.CharField(blank=True, max_length=15, verbose_name='contact number')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1, verbose_name='sex')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='HousePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.PositiveIntegerField(default=0)),
                ('move_in_date', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True, verbose_name='Move-in date range')),
                ('move_out_date', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True, verbose_name='Move-out date range')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('S', 'Selected'), ('P', 'Published')], default='I', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist', models.ManyToManyField(blank=True, to='house.House')),
            ],
        ),
    ]
