# Generated by Django 2.0.4 on 2018-11-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0002_auto_20181119_2231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housepreference',
            name='home_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='house.HomeType', verbose_name='Home Type'),
        ),
        migrations.AddField(
            model_name='housepreference',
            name='locations',
            field=models.ManyToManyField(blank=True, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='housepreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.TenantProfile'),
        ),
        migrations.AddField(
            model_name='additionaltenant',
            name='house_pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.HousePreference'),
        ),
    ]
