# Generated by Django 2.0.4 on 2019-03-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20181122_1946'),
        ('user_custom', '0005_auto_20190305_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='customer_id',
        ),
    ]
