# Generated by Django 2.0.4 on 2019-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20181122_1946'),
        ('user_custom', '0006_auto_20190418_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='customer_id',
        ),
    ]
