# Generated by Django 2.0.4 on 2019-01-16 21:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Coupon/Voucher Code')),
                ('verbose', models.TextField(help_text='Example: 50% off for New users', verbose_name='Title')),
                ('description', models.TextField(blank=True)),
                ('tnc', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('value_type', models.CharField(choices=[('F', 'Flat'), ('P', 'Percentage')], max_length=1)),
                ('invert_discount', models.BooleanField(default=False, help_text='Default behaviour is Discount. Selecting it will change the behaviour to extra charge.')),
                ('principal', models.CharField(choices=[('R', 'Total Rent'), ('S', 'Service Fee'), ('N', 'Net Amount')], max_length=1)),
                ('value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('active', models.BooleanField(default=False)),
                ('applied_by', models.CharField(choices=[('T', 'Tenant'), ('H', 'Home Owner')], max_length=1)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users which are allowed to use this Promotional Code. Selecting None will make it applicable to all.', to=settings.AUTH_USER_MODEL)),
                ('applicable_on', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'application'), ('model', 'application')), models.Q(('app_label', 'house'), ('model', 'house')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalCodeReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.PromotionalCode')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promotionalcodereferee',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.Referee'),
        ),
    ]
