# Generated by Django 2.0.4 on 2019-03-19 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcode',
            name='invert_discount',
        ),
        migrations.RemoveField(
            model_name='promotionalcode',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='promotionalcode',
            name='value',
        ),
        migrations.RemoveField(
            model_name='promotionalcode',
            name='value_type',
        ),
        migrations.AddField(
            model_name='promotionalcode',
            name='behaviour',
            field=models.CharField(choices=[('A', 'Percentage Discount'), ('B', 'Flat Discount')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotionalcode',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who are allowed to use this Promotional Code. Selecting None will make it applicable to all.', to=settings.AUTH_USER_MODEL),
        ),
    ]
