# Generated by Django 2.2.10 on 2020-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_auto_20181122_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(default='Default Text', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='operation_type',
            field=models.CharField(choices=[('C', 'Create'), ('R', 'Read'), ('U', 'Update'), ('D', 'Delete')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
