# Generated by Django 2.0.4 on 2019-03-03 15:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def create_default_payment_gateways(apps, schema_editor):
    PaymentGateway = apps.get_model('admin_custom', 'PaymentGateway')
    stripe = PaymentGateway(name='Stripe', code='STRIPE', meta={})
    stripe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_auto_20181122_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Internal Identifier', max_length=10, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(help_text='For internal data and financial assessment only. This should not be used to store any data required for or by the payment gateway for monetary transactions.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_payment_gateways)
    ]
